# Generated by Django 6.0.6 on 2026-07-15 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True, help_text="Загрузите фото", null=True, upload_to="users/avatar/", verbose_name="Аватар"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="country",
            field=models.CharField(
                blank=True, help_text="Укажите страну", max_length=20, null=True, verbose_name="Страна"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                help_text="Введите адрес электронной почты", max_length=254, unique=True, verbose_name="email"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(
                blank=True, help_text="Введите номер телефона", max_length=20, null=True, verbose_name="Номер телефона"
            ),
        ),
    ]
