# Generated by Django 6.0.6 on 2026-07-10 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "title",
                    models.CharField(help_text="Введите название статьи", max_length=200, verbose_name="Заголовок"),
                ),
                ("content", models.TextField(help_text="Основной текст статьи", verbose_name="Содержимое")),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="blog_previews/", verbose_name="Превью (изображение)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")),
                (
                    "is_published",
                    models.BooleanField(
                        default=False,
                        help_text="Отметьте, если статья должна быть видна на сайте",
                        verbose_name="Опубликовано",
                    ),
                ),
                (
                    "view_count",
                    models.PositiveIntegerField(
                        db_index=True, default=0, editable=False, verbose_name="Количество просмотров"
                    ),
                ),
            ],
            options={
                "verbose_name": "Запись блога",
                "verbose_name_plural": "Записи блога",
                "ordering": ["-created_at"],
            },
        ),
    ]
