# Generated by Django 6.0.6 on 2026-07-15 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_published",
            field=models.BooleanField(
                default=False,
                help_text="Отметьте, если продукт должен быть виден на сайте",
                verbose_name="Опубликовано",
            ),
        ),
    ]
